import Link from "next/link";
import { getAdminDashboard } from "@/features/admin/server/admin-service";

export default async function AdminPage() {
  const d = await getAdminDashboard();
  const cards = [
    { value: d.pendingTeachers, label: "Chờ phê duyệt", note: "Giáo viên mới", icon: "✦", style: "from-amber-100 to-orange-50 text-orange-700", bubble: "bg-orange-500" },
    { value: d.activeTeachers, label: "Giáo viên", note: "Đang hoạt động", icon: "✓", style: "from-emerald-100 to-teal-50 text-teal-700", bubble: "bg-teal-500" },
    { value: d.students, label: "Học sinh", note: "Toàn hệ thống", icon: "◉", style: "from-cyan-100 to-sky-50 text-sky-700", bubble: "bg-sky-500" },
    { value: d.classrooms, label: "Lớp học", note: "Đang quản lý", icon: "▦", style: "from-violet-100 to-fuchsia-50 text-violet-700", bubble: "bg-violet-500" },
  ];
  return <main className="p-5 sm:p-7 lg:p-10">
    <section className="relative overflow-hidden rounded-2xl bg-gradient-to-r from-violet-600 via-purple-600 to-fuchsia-500 p-7 text-white shadow-xl shadow-violet-200/70 sm:p-9"><div className="absolute -right-10 -top-16 size-52 rounded-full border-[32px] border-white/10" /><div className="absolute bottom-3 right-32 size-16 rotate-12 rounded-2xl bg-amber-300/80" /><p className="text-sm font-bold uppercase tracking-[0.22em] text-violet-100">Không gian điều hành</p><h1 className="mt-3 max-w-xl text-3xl font-black tracking-tight sm:text-4xl">Mọi hoạt động học tập,<br />trong một góc nhìn.</h1><p className="mt-4 max-w-lg text-sm leading-6 text-violet-100">Theo dõi giáo viên, học sinh và lớp học nhanh chóng mà vẫn giữ dữ liệu an toàn.</p></section>
    <div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map((card) => <article className={`relative overflow-hidden rounded-2xl bg-gradient-to-br p-5 shadow-sm ring-1 ring-white ${card.style}`} key={card.label}><div className={`flex size-10 items-center justify-center rounded-2xl text-lg font-black text-white shadow-sm ${card.bubble}`}>{card.icon}</div><p className="mt-5 text-4xl font-black tracking-tight">{card.value}</p><p className="mt-1 font-black text-slate-800">{card.label}</p><p className="text-xs font-semibold opacity-70">{card.note}</p><div className="absolute -bottom-8 -right-8 size-24 rounded-full bg-white/40" /></article>)}</div>
    <section className="mt-6 grid gap-5 lg:grid-cols-[1.35fr_0.65fr]"><div className="rounded-2xl bg-white/85 p-6 shadow-sm ring-1 ring-violet-100 backdrop-blur"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-fuchsia-600">Ưu tiên hôm nay</p><h2 className="mt-1 text-2xl font-black">Cần xử lý</h2></div><span className="flex size-11 items-center justify-center rounded-2xl bg-fuchsia-50 text-xl text-fuchsia-600">!</span></div>{d.pendingTeachers ? <div className="mt-5 flex items-center justify-between rounded-2xl bg-amber-50 p-4"><div><p className="font-black">{d.pendingTeachers} giáo viên chờ duyệt</p><p className="mt-1 text-sm text-slate-500">Kiểm tra hồ sơ để kích hoạt tài khoản.</p></div><Link className="rounded-xl bg-teal-600 px-4 py-2 text-sm font-black text-white hover:bg-teal-700" href="/admin/teachers?status=PENDING">Xem ngay</Link></div> : <div className="mt-5 rounded-2xl bg-emerald-50 p-4 font-semibold text-emerald-700">✓ Không có giáo viên nào đang chờ duyệt.</div>}{d.suspendedAccounts ? <p className="mt-3 rounded-2xl bg-rose-50 p-4 text-sm font-bold text-rose-700">{d.suspendedAccounts} tài khoản đang tạm khóa.</p> : null}</div><div className="rounded-2xl bg-gradient-to-br from-indigo-500 to-violet-500 p-6 text-white shadow-lg shadow-violet-200"><p className="text-xs font-black uppercase tracking-[0.18em] text-indigo-100">Gợi ý</p><h2 className="mt-3 text-xl font-black">Giữ hệ thống gọn gàng</h2><p className="mt-3 text-sm leading-6 text-indigo-50">Duyệt tài khoản mới thường xuyên và kiểm tra Audit log khi có thay đổi quan trọng.</p><Link className="mt-5 inline-block text-sm font-black text-amber-200" href="/admin/audit-log">Mở nhật ký →</Link></div></section>
  </main>;
}
