import Link from "next/link";
import { notFound } from "next/navigation";
import { AnswerAssessmentForm } from "@/features/assignment/components/answer-assessment-form";
import { getTeacherSubmissionResult } from "@/features/assignment/server/queries";

export default async function SubmissionResultPage({ params }: { params: Promise<{ submissionId: string }> }) {
  const { submissionId } = await params; const data = await getTeacherSubmissionResult(submissionId); if (!data) notFound();
  const autoMax = data.answers.filter((answer) => answer.question.task?.skill !== "SPEAKING").reduce((sum, answer) => sum + answer.question.points, 0);
  const speaking = data.answers.filter((answer) => answer.question.task?.skill === "SPEAKING");
  return <main className="mx-auto max-w-4xl px-5 py-8 sm:px-8"><Link className="text-sm font-semibold text-teal-700" href={`/teacher/assignments/${data.assignment.id}/results`}>← Kết quả lớp</Link><div className="mt-5 rounded-2xl bg-gradient-to-r from-teal-50 to-cyan-50 p-6 ring-1 ring-teal-100"><p className="text-xs font-bold tracking-[0.18em] text-teal-700">BÀI LÀM HỌC SINH</p><h1 className="mt-2 text-3xl font-bold">{data.student.full_name}</h1><p className="mt-2 text-slate-600">{data.assignment.title} · Điểm tự động: <b>{data.submission.auto_score ?? 0}/{autoMax}</b></p></div>
    <section className="mt-7"><h2 className="text-2xl font-bold">Speaking · Giáo viên chấm</h2><p className="mt-1 text-slate-500">Nghe từng bản thu, nhập điểm và nhận xét ngắn cho học sinh.</p><div className="mt-4 space-y-4">{speaking.map((answer, index) => <article key={answer.id} className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><p className="text-sm font-bold text-violet-700">Câu nói {index + 1} · {answer.question.points} điểm</p><h3 className="mt-2 text-lg font-bold">{answer.question.prompt}</h3>{answer.audio_url ? <audio controls preload="metadata" src={answer.audio_url} className="mt-4 w-full" /> : <p className="mt-4 rounded-xl bg-rose-50 p-3 text-sm font-semibold text-rose-700">Không tìm thấy bản thu âm.</p>}<AnswerAssessmentForm answerId={answer.id} maxPoints={answer.question.points} initialScore={answer.teacher_score} initialFeedback={answer.teacher_feedback} /></article>)}</div></section>
    <details className="mt-7 rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><summary className="cursor-pointer text-lg font-bold">Xem đáp án Listening, Reading và Writing</summary><div className="mt-4 space-y-3">{data.answers.filter((answer) => answer.question.task?.skill !== "SPEAKING").map((answer) => <div key={answer.id} className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-bold text-teal-700">{answer.question.task?.skill}</p><p className="mt-1 font-semibold">{answer.question.prompt}</p><p className="mt-2 text-sm">Điểm tự động: <b>{answer.auto_score ?? 0}/{answer.question.points}</b></p></div>)}</div></details>
  </main>;
}
